/** Shared Start Page renderer — used by the editor preview (srcDoc) and by apps/startpage (SSR). Pure function, no DOM. */
export interface StartPageData { nickname: string; theme: any; header: any; blocks: any[] }

export const THEME_PRESETS: Record<string, any> = {
  sand: { background: { type: 'color', value: '#FCFBF9' }, button: { style: 'filled', radius: 'pill', color: '#6DB44F', textColor: '#0B1F0B' }, font: { heading: 'Inter', body: 'Inter' }, banner: 'none', text: '#1F1D1A' },
  midnight: { background: { type: 'color', value: '#101828' }, button: { style: 'filled', radius: 'pill', color: '#8FC67D', textColor: '#0B1F0B' }, font: { heading: 'Inter', body: 'Inter' }, banner: 'none', text: '#F3F1EC' },
  forest: { background: { type: 'gradient', value: 'linear-gradient(160deg,#0F2A1D,#1E4D33)' }, button: { style: 'outline', radius: 'rounded', color: '#C9F2A8', textColor: '#C9F2A8' }, font: { heading: 'DM Serif Display', body: 'Inter' }, banner: 'wave', text: '#F3F7EE' },
  ocean: { background: { type: 'gradient', value: 'linear-gradient(160deg,#0B3C5D,#1F7A8C)' }, button: { style: 'filled', radius: 'pill', color: '#FFFFFF', textColor: '#0B3C5D' }, font: { heading: 'Space Grotesk', body: 'Inter' }, banner: 'circle', text: '#FFFFFF' },
  sunset: { background: { type: 'gradient', value: 'linear-gradient(160deg,#FF8A5B,#EA5455)' }, button: { style: 'filled', radius: 'rounded', color: '#FFF1E6', textColor: '#7A1F1F' }, font: { heading: 'Nunito', body: 'Nunito' }, banner: 'block', text: '#FFFFFF' },
  lavender: { background: { type: 'color', value: '#F3F0FF' }, button: { style: 'soft', radius: 'pill', color: '#7C3AED', textColor: '#FFFFFF' }, font: { heading: 'Inter', body: 'Inter' }, banner: 'none', text: '#2E1065' },
  mono: { background: { type: 'color', value: '#FFFFFF' }, button: { style: 'outline', radius: 'square', color: '#111111', textColor: '#111111' }, font: { heading: 'IBM Plex Mono', body: 'IBM Plex Mono' }, banner: 'none', text: '#111111' },
  candy: { background: { type: 'color', value: '#FFE4F1' }, button: { style: 'filled', radius: 'pill', color: '#D925AC', textColor: '#FFFFFF' }, font: { heading: 'Nunito', body: 'Nunito' }, banner: 'circle', text: '#4A0D3B' },
  slate: { background: { type: 'color', value: '#1F2937' }, button: { style: 'soft', radius: 'rounded', color: '#60A5FA', textColor: '#0B1F3A' }, font: { heading: 'Inter', body: 'Inter' }, banner: 'none', text: '#E5E7EB' },
  olive: { background: { type: 'color', value: '#F1F3E6' }, button: { style: 'filled', radius: 'rounded', color: '#556B2F', textColor: '#FFFFFF' }, font: { heading: 'Georgia', body: 'Inter' }, banner: 'wave', text: '#1F2A10' },
  coral: { background: { type: 'color', value: '#FFF5F2' }, button: { style: 'filled', radius: 'pill', color: '#FF6F59', textColor: '#2B0A05' }, font: { heading: 'Space Grotesk', body: 'Inter' }, banner: 'none', text: '#2B0A05' },
  sky: { background: { type: 'gradient', value: 'linear-gradient(180deg,#E0F2FE,#FFFFFF)' }, button: { style: 'filled', radius: 'pill', color: '#0284C7', textColor: '#FFFFFF' }, font: { heading: 'Inter', body: 'Inter' }, banner: 'circle', text: '#0C4A6E' },
  paper: { background: { type: 'color', value: '#FAF7F0' }, button: { style: 'outline', radius: 'rounded', color: '#5B4636', textColor: '#5B4636' }, font: { heading: 'DM Serif Display', body: 'Georgia' }, banner: 'none', text: '#2B1D12' },
  ink: { background: { type: 'color', value: '#000000' }, button: { style: 'filled', radius: 'square', color: '#FFFFFF', textColor: '#000000' }, font: { heading: 'Space Grotesk', body: 'Inter' }, banner: 'block', text: '#FFFFFF' },
  mint: { background: { type: 'color', value: '#E6FFF5' }, button: { style: 'soft', radius: 'pill', color: '#0E9384', textColor: '#FFFFFF' }, font: { heading: 'Inter', body: 'Inter' }, banner: 'wave', text: '#063B35' },
  plum: { background: { type: 'gradient', value: 'linear-gradient(160deg,#3B0764,#701A75)' }, button: { style: 'filled', radius: 'pill', color: '#F0ABFC', textColor: '#3B0764' }, font: { heading: 'Nunito', body: 'Inter' }, banner: 'none', text: '#FDF4FF' },
};

const esc = (s: unknown) => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
const safeUrl = (u: unknown) => { const s = String(u ?? ''); return /^https?:\/\//i.test(s) || /^mailto:/i.test(s) ? esc(s) : '#'; };
const ICONS: Record<string, string> = { instagram: 'IG', x: 'X', tiktok: 'TT', youtube: 'YT', linkedin: 'in', facebook: 'f', threads: '@', bluesky: 'bs', mastodon: 'm', pinterest: 'P', website: '🌐', email: '✉' };

export function renderStartPage(d: StartPageData, slug: string, opts: { preview?: boolean; goBase?: string } = {}): string {
  const t = d.theme; const go = (blockId: string, url: string) => (opts.preview ? safeUrl(url) : `${opts.goBase ?? ''}/go/${esc(blockId)}?u=${encodeURIComponent(url)}`);
  const radius = t.button.radius === 'pill' ? '999px' : t.button.radius === 'rounded' ? '12px' : '2px';
  const btn = t.button.style === 'filled' ? `background:${esc(t.button.color)};color:${esc(t.button.textColor)};border:2px solid ${esc(t.button.color)}` : t.button.style === 'outline' ? `background:transparent;color:${esc(t.button.color)};border:2px solid ${esc(t.button.color)}` : `background:${esc(t.button.color)}22;color:${esc(t.button.color)};border:2px solid transparent`;
  const bg = t.background.type === 'image' || t.background.type === 'gif' ? `background:url(${safeUrl(t.background.value)}) center/cover fixed` : `background:${esc(t.background.value)}`;
  const banner = t.banner === 'wave' ? `<svg class="banner" viewBox="0 0 400 60" preserveAspectRatio="none" aria-hidden="true"><path d="M0 30 Q100 0 200 30 T400 30 V60 H0Z" fill="${esc(t.button.color)}" opacity=".25"/></svg>` : t.banner === 'block' ? `<div class="banner" style="height:96px;background:${esc(t.button.color)};opacity:.25" aria-hidden="true"></div>` : t.banner === 'circle' ? `<div class="banner" style="height:120px;background:radial-gradient(circle at 50% 0,${esc(t.button.color)}55,transparent 70%)" aria-hidden="true"></div>` : '';
  const fonts = Array.from(new Set([t.font.heading, t.font.body])).filter(f => !['Inter', 'Georgia'].includes(f)).map(f => `family=${encodeURIComponent(f)}:wght@400;600;700`).join('&');
  const blocks = d.blocks.filter(b => !b.hidden).map(b => {
    switch (b.type) {
      case 'link': return `<a class="btn" href="${go(b.id, b.url)}" ${opts.preview ? '' : 'rel="noopener"'}>${b.thumbUrl ? `<img src="${safeUrl(b.thumbUrl)}" alt="" class="thumb">` : ''}<span>${esc(b.label)}</span></a>`;
      case 'text': return `<p class="text">${esc(b.body).replace(/\n/g, '<br>')}</p>`;
      case 'image': return b.src ? (b.url ? `<a href="${go(b.id, b.url)}" class="img"><img src="${safeUrl(b.src)}" alt="${esc(b.alt)}"></a>` : `<img class="img" src="${safeUrl(b.src)}" alt="${esc(b.alt)}">`) : '';
      case 'imageGrid': return `<div class="grid" style="grid-template-columns:repeat(${Number(b.columns) || 3},1fr)">${(b.items ?? []).slice(0, 18).map((i: any) => i.url ? `<a href="${go(b.id, i.url)}"><img src="${safeUrl(i.src)}" alt="${esc(i.alt)}"></a>` : `<img src="${safeUrl(i.src)}" alt="${esc(i.alt)}">`).join('')}</div>`;
      case 'video': { const yt = /(?:youtu\.be\/|v=|shorts\/)([\w-]{11})/.exec(b.url ?? '')?.[1]; const vm = /vimeo\.com\/(\d+)/.exec(b.url ?? '')?.[1]; return yt ? `<iframe class="embed" src="https://www.youtube-nocookie.com/embed/${yt}" title="Video" loading="lazy" allowfullscreen></iframe>` : vm ? `<iframe class="embed" src="https://player.vimeo.com/video/${vm}" title="Video" loading="lazy" allowfullscreen></iframe>` : b.url ? `<a class="btn" href="${go(b.id, b.url)}">▶ Watch video</a>` : ''; }
      case 'youtubeLatest': return b.channelId ? `<iframe class="embed" src="https://www.youtube-nocookie.com/embed?listType=playlist&list=UU${esc(String(b.channelId).replace(/^UC/, ''))}" title="Latest videos" loading="lazy" allowfullscreen></iframe>` : '';
      case 'spotify': { const m = /open\.spotify\.com\/(track|album|playlist|episode|show)\/([\w]+)/.exec(b.url ?? ''); return m ? `<iframe class="embed" style="height:152px" src="https://open.spotify.com/embed/${m[1]}/${m[2]}" title="Spotify" loading="lazy" allow="encrypted-media"></iframe>` : ''; }
      case 'social': return `<div class="social">${(d.header.socialIcons ?? []).map((s: any) => `<a href="${go(b.id, s.url)}" aria-label="${esc(s.network)}">${ICONS[s.network] ?? '•'}</a>`).join('')}</div>`;
      case 'mailchimp': return b.action ? `<form class="mc" action="${safeUrl(b.action)}" method="post" target="_blank"><label class="sr" for="mce-EMAIL">Email address</label><input id="mce-EMAIL" type="email" name="EMAIL" placeholder="you@example.com" required><button class="btn" type="submit">${esc(b.buttonLabel ?? 'Subscribe')}</button></form>` : '';
      case 'updates': return (b.items ?? []).length ? `<section class="updates" aria-label="Latest updates">${(b.items ?? []).slice(0, b.count ?? 5).map((u: any) => `<article class="upd">${u.media?.[0]?.thumbUrl ? `<img src="${safeUrl(u.media[0].thumbUrl)}" alt="">` : ''}<p>${esc(u.text)}</p>${u.link ? `<a href="${go(b.id, u.link)}">Read more →</a>` : ''}</article>`).join('')}</section>` : opts.preview ? `<p class="text muted">Your latest posts scheduled to this Start Page appear here.</p>` : '';
      case 'divider': return '<hr>';
      default: return '';
    }
  }).join('\n');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(d.header.title ?? d.nickname)}</title><meta name="description" content="${esc(d.header.description ?? d.header.tagline ?? '')}">${fonts ? `<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?${fonts}&display=swap">` : ''}
<style>*{box-sizing:border-box}body{margin:0;${bg};color:${esc(t.text)};font-family:"${esc(t.font.body)}",system-ui,sans-serif;min-height:100vh}.wrap{max-width:560px;margin:0 auto;padding:24px 20px 60px}.banner{display:block;width:100%;margin:-24px -20px 0;width:calc(100% + 40px)}h1{font-family:"${esc(t.font.heading)}",system-ui,sans-serif;font-size:26px;margin:12px 0 4px;text-align:center}.tag{text-align:center;opacity:.8;margin:0 0 20px}.logo{width:88px;height:88px;border-radius:50%;display:block;margin:8px auto 0;object-fit:cover;border:3px solid rgba(255,255,255,.6)}.btn{display:flex;align-items:center;justify-content:center;gap:10px;width:100%;padding:14px 16px;margin:10px 0;border-radius:${radius};${btn};font-weight:600;text-decoration:none;font-size:16px;transition:transform .12s}.btn:hover{transform:translateY(-1px)}.btn:focus-visible{outline:3px solid ${esc(t.text)};outline-offset:2px}.thumb{width:36px;height:36px;border-radius:8px;object-fit:cover}.text{text-align:center;line-height:1.6;margin:14px 0}.muted{opacity:.6}.img,.img img{width:100%;border-radius:14px;display:block;margin:12px 0}.grid{display:grid;gap:6px;margin:12px 0}.grid img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:10px;display:block}.embed{width:100%;aspect-ratio:16/9;border:0;border-radius:14px;margin:12px 0}.social{display:flex;justify-content:center;gap:12px;margin:14px 0}.social a{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;background:${esc(t.button.color)}22;color:${esc(t.text)};text-decoration:none;font-weight:700;font-size:13px}.mc{display:flex;gap:8px;margin:12px 0}.mc input{flex:1;padding:12px;border-radius:${radius};border:2px solid ${esc(t.button.color)}55;background:rgba(255,255,255,.9);color:#111}.mc .btn{width:auto;margin:0}.sr{position:absolute;left:-9999px}.updates{margin:16px 0}.upd{background:rgba(255,255,255,.12);border:1px solid ${esc(t.button.color)}33;border-radius:14px;padding:12px;margin:8px 0}.upd img{width:100%;border-radius:10px;margin-bottom:8px}.upd p{margin:0 0 6px;white-space:pre-wrap}.upd a{color:${esc(t.button.color)};font-weight:600}hr{border:0;border-top:1px solid ${esc(t.text)}33;margin:18px 0}footer{text-align:center;opacity:.6;font-size:12px;margin-top:30px}footer a{color:inherit}@media(prefers-reduced-motion:reduce){.btn{transition:none}}</style></head>
<body><main class="wrap">${banner}${d.header.logoUrl ? `<img class="logo" src="${safeUrl(d.header.logoUrl)}" alt="">` : ''}<h1>${esc(d.header.title ?? d.nickname)}</h1>${d.header.tagline ? `<p class="tag">${esc(d.header.tagline)}</p>` : ''}${(d.header.socialIcons ?? []).length && !d.blocks.some(b => b.type === 'social' && !b.hidden) ? `<div class="social">${d.header.socialIcons.map((s: any) => `<a href="${go('header', s.url)}" aria-label="${esc(s.network)}">${ICONS[s.network] ?? '•'}</a>`).join('')}</div>` : ''}
${blocks}
<footer>Made with <a href="https://relay.app/start-page?ref=${esc(slug)}">Cadence</a></footer></main></body></html>`;
}
