import { gql } from 'graphql-request';

export const CHANNEL_FIELDS = gql`fragment ChannelFields on Channel { id network subtype externalId displayName handle avatarUrl timezone status statusReason isPaused notifyByDefault postingGoalPerWeek sortOrder meta queueCount publishedThisWeek myAccess lastHealthCheckAt groupIds }`;
export const TARGET_FIELDS = gql`fragment TargetFields on PostTarget { id postId channelId status schedulingType isCustomTime customized dueAt queuePosition text media thread firstComment metadata shortLinks externalUrl publishedAt attemptCount failureCode failureMessage metrics channel { id network displayName handle avatarUrl timezone } post { id status scheduleMode baseText baseMedia linkPreview aiAssisted autoRepost notesCount createdBy { id name email avatarUrl } tags { id name color } approval { requestedByAccountId requestedAt decision reason } targets { id channelId } } }`;

export const Q = {
  me: gql`query Me { me { id email name avatarUrl } organization { id name slug plan entitlements settings require2fa } }`,
  channels: gql`${CHANNEL_FIELDS} query Channels { channels { ...ChannelFields } }`,
  channel: gql`${CHANNEL_FIELDS} query Channel($id: ID!) { channel(id: $id) { ...ChannelFields scheduleByDay schedule { id weekday minuteOfDay enabled source } suggestedSlots } }`,
  channelGroups: gql`query Groups { organization { channelGroups { id name channelIds } } }`,
  networks: gql`query Networks { networks { network label needsHint note configured rules } }`,
  targets: gql`${TARGET_FIELDS} query Targets($filter: PostFilter, $first: Int, $after: String) { targets(filter: $filter, first: $first, after: $after) { edges { cursor node { ...TargetFields } } pageInfo { hasNextPage endCursor } } }`,
  targetsWithMetrics: gql`${TARGET_FIELDS} query Sent($filter: PostFilter, $first: Int, $after: String) { targets(filter: $filter, first: $first, after: $after) { edges { cursor node { ...TargetFields metrics } } pageInfo { hasNextPage endCursor } } }`,
  post: gql`${TARGET_FIELDS} query Post($id: ID!) { post(id: $id) { id status scheduleMode baseText baseMedia linkPreview tags { id name color } targets { ...TargetFields } notes { id body author { id name email avatarUrl } createdAt editedAt } approval { requestedByAccountId requestedAt decision reason } } }`,
  tags: gql`query Tags { tags { id name color postCount } }`,
  notifications: gql`query Notifications { notifications(take: 20) { id type title body url readAt createdAt } notificationUnreadCount }`,
  calendarEvents: gql`query CalEvents($from: DateTime, $to: DateTime) { calendarEvents(from: $from, to: $to) { id title startDate endDate color note } }`,
  savedMentions: gql`query SavedMentions { savedMentions { id label value network } }`,
  hashtagGroups: gql`query HashtagGroups { hashtagGroups { id name hashtags } }`,
  savedReplies: gql`query SavedReplies { savedReplies { id title body } }`,
  ideas: gql`query Ideas($groupId: ID, $tagId: ID, $search: String, $first: Int, $after: String) { ideaGroups { id name sortOrder } ideas(groupId: $groupId, tagId: $tagId, search: $search, first: $first, after: $after) { edges { node { id title body media links groupId sortOrder aiGenerated usedAt tags { id name color } createdAt } } pageInfo { hasNextPage endCursor } } }`,
  templates: gql`query Templates($category: String) { templates(category: $category) { id title body category isLibrary ownerAccountId } }`,
  linkPreview: gql`query Preview($url: String!) { linkPreview(url: $url) { url title description image siteName } }`,
  validatePost: gql`query Validate($input: CreatePostInput!) { validatePost(input: $input) { channelId issues { level field message } } }`,
  channelLookup: gql`query Lookup($channelId: ID!, $what: String!, $args: JSON) { channelLookup(channelId: $channelId, what: $what, args: $args) }`,
  members: gql`query Members { organization { members { id role status invitedEmail account { id email name avatarUrl } channelGrants { channelId publish community } createdAt } } }`,
  comments: gql`query Comments($filter: CommentFilter, $sort: String, $first: Int, $after: String) { comments(filter: $filter, sort: $sort, first: $first, after: $after) { edges { node { id channelId externalPostId externalId parentExternalId kind authorName authorHandle authorAvatarUrl text attachments externalCreatedAt likeCount isHidden isOurs repliedAt resolvedAt labels sentiment triage assignedToAccountId assignee { id name email avatarUrl } waitingMinutes capabilities channel { id network displayName avatarUrl } postTarget { id text media externalUrl metrics } replies { id text authorName isOurs externalCreatedAt } } } pageInfo { hasNextPage endCursor } } unansweredCount }`,
  commentGroups: gql`query CommentGroups($filter: CommentFilter) { commentPostGroups(filter: $filter) { externalPostId channelId count unanswered latestAt postTarget { id text media externalUrl channel { id network displayName avatarUrl } } } }`,
  insightsSummary: gql`query Summary($range: InsightsRange!) { insightsSummary(range: $range) { metric current previous change } }`,
  insightsSeries: gql`query Series($range: InsightsRange!, $metrics: [String!]!, $bucket: String) { insightsSeries(range: $range, metrics: $metrics, bucket: $bucket) { day metric value } }`,
  insightsPosts: gql`${TARGET_FIELDS} query InsightsPosts($range: InsightsRange!, $sortBy: String, $first: Int, $after: String) { insightsPosts(range: $range, sortBy: $sortBy, first: $first, after: $after) { edges { node { ...TargetFields metrics } } pageInfo { hasNextPage endCursor } } }`,
  insightsAudience: gql`query Audience($channelId: ID!) { insightsAudience(channelId: $channelId) { dimension bucket value } }`,
  insightsHashtags: gql`query Hashtags($range: InsightsRange!) { insightsHashtags(range: $range) { hashtag posts engagements impressions } }`,
  apiKeys: gql`query ApiKeys { apiKeys { id name prefix scopes lastUsedAt createdAt } }`,
  savedViews: gql`query Views($area: String) { savedViews(area: $area) { id area name filters } }`,
  notificationPrefs: gql`query Prefs { notificationPrefs }`,
  auditLog: gql`query Audit($take: Int, $before: DateTime) { auditLog(take: $take, before: $before) { id action entity entityId actorAccountId diff createdAt } }`,
};

export const M = {
  createPost: gql`mutation CreatePost($input: CreatePostInput!) { createPost(input: $input) { id status targets { id channelId status dueAt } } }`,
  updatePost: gql`mutation UpdatePost($id: ID!, $input: UpdatePostInput!) { updatePost(id: $id, input: $input) { id status } }`,
  deletePost: gql`mutation DeletePost($id: ID!) { deletePost(id: $id) }`,
  duplicatePost: gql`mutation Dup($id: ID!, $asDraft: Boolean) { duplicatePost(id: $id, asDraft: $asDraft) { id } }`,
  approvePost: gql`mutation Approve($id: ID!, $mode: ScheduleMode, $dueAt: DateTime) { approvePost(id: $id, mode: $mode, dueAt: $dueAt) }`,
  rejectPost: gql`mutation Reject($id: ID!, $reason: String) { rejectPost(id: $id, reason: $reason) }`,
  requestApproval: gql`mutation ReqApproval($id: ID!) { requestApproval(id: $id) }`,
  createShareLink: gql`mutation ShareLink($postId: ID!) { createShareLink(postId: $postId) }`,
  markNotificationRead: gql`mutation MarkNoti($id: ID!) { markNotificationRead(id: $id) }`,
  markAllNotificationsRead: gql`mutation MarkAllNoti { markAllNotificationsRead }`,
  createCalendarEvent: gql`mutation CreateCalEvent($title: String!, $startDate: DateTime!, $endDate: DateTime, $color: String, $note: String) { createCalendarEvent(title: $title, startDate: $startDate, endDate: $endDate, color: $color, note: $note) { id } }`,
  deleteCalendarEvent: gql`mutation DeleteCalEvent($id: ID!) { deleteCalendarEvent(id: $id) }`,
  saveSavedMention: gql`mutation SaveMention($id: ID, $label: String!, $value: String!, $network: String) { saveSavedMention(id: $id, label: $label, value: $value, network: $network) { id } }`,
  deleteSavedMention: gql`mutation DeleteMention($id: ID!) { deleteSavedMention(id: $id) }`,
  revertApproval: gql`mutation Revert($id: ID!) { revertApproval(id: $id) }`,
  addNote: gql`mutation AddNote($postId: ID!, $body: String!) { addNote(postId: $postId, body: $body) { id } }`,
  moveToTop: gql`mutation MoveTop($targetId: ID!) { moveToTop(targetId: $targetId) }`,
  moveTarget: gql`mutation Move($targetId: ID!, $direction: String!) { moveTarget(targetId: $targetId, direction: $direction) }`,
  swapTargets: gql`mutation Swap($aId: ID!, $bId: ID!) { swapTargets(aId: $aId, bId: $bId) }`,
  moveToNextSlot: gql`mutation NextSlot($targetId: ID!) { moveToNextSlot(targetId: $targetId) }`,
  setTargetTime: gql`mutation SetTime($targetId: ID!, $dueAt: DateTime!) { setTargetTime(targetId: $targetId, dueAt: $dueAt) }`,
  addToQueue: gql`mutation AddToQueue($targetId: ID!) { addToQueue(targetId: $targetId) }`,
  shareNow: gql`mutation ShareNow($targetId: ID!) { shareNow(targetId: $targetId) }`,
  retryNow: gql`mutation Retry($targetId: ID!) { retryNow(targetId: $targetId) }`,
  moveToDrafts: gql`mutation ToDrafts($targetId: ID!) { moveToDrafts(targetId: $targetId) }`,
  markNotificationDone: gql`mutation NotifyDone($targetId: ID!, $externalUrl: String) { markNotificationDone(targetId: $targetId, externalUrl: $externalUrl) }`,
  updateChannel: gql`mutation UpdateChannel($id: ID!, $timezone: String, $isPaused: Boolean, $notifyByDefault: Boolean, $postingGoalPerWeek: Int, $displayName: String, $meta: JSON) { updateChannel(id: $id, timezone: $timezone, isPaused: $isPaused, notifyByDefault: $notifyByDefault, postingGoalPerWeek: $postingGoalPerWeek, displayName: $displayName, meta: $meta) { id } }`,
  setPostingSchedule: gql`mutation SetSchedule($channelId: ID!, $slots: [PostingSlotInput!]!) { setPostingSchedule(channelId: $channelId, slots: $slots) { id } }`,
  shuffleQueue: gql`mutation Shuffle($channelId: ID!) { shuffleQueue(channelId: $channelId) }`,
  reorderChannels: gql`mutation ReorderChannels($ids: [ID!]!) { reorderChannels(ids: $ids) }`,
  refreshChannel: gql`mutation Refresh($id: ID!) { refreshChannel(id: $id) { id status statusReason } }`,
  removeChannel: gql`mutation RemoveChannel($id: ID!) { removeChannel(id: $id) }`,
  createChannelGroup: gql`mutation CreateGroup($name: String!, $channelIds: [ID!]!) { createChannelGroup(name: $name, channelIds: $channelIds) { id } }`,
  updateChannelGroup: gql`mutation UpdateGroup($id: ID!, $name: String, $channelIds: [ID!]) { updateChannelGroup(id: $id, name: $name, channelIds: $channelIds) { id } }`,
  deleteChannelGroup: gql`mutation DeleteGroup($id: ID!) { deleteChannelGroup(id: $id) }`,
  createTag: gql`mutation CreateTag($name: String!, $color: String!) { createTag(name: $name, color: $color) { id name color } }`,
  updateTag: gql`mutation UpdateTag($id: ID!, $name: String, $color: String) { updateTag(id: $id, name: $name, color: $color) { id } }`,
  deleteTag: gql`mutation DeleteTag($id: ID!) { deleteTag(id: $id) }`,
  saveHashtagGroup: gql`mutation SaveHG($id: ID, $name: String!, $hashtags: [String!]!) { saveHashtagGroup(id: $id, name: $name, hashtags: $hashtags) { id } }`,
  deleteHashtagGroup: gql`mutation DelHG($id: ID!) { deleteHashtagGroup(id: $id) }`,
  saveSavedReply: gql`mutation SaveReply($id: ID, $title: String!, $body: String!) { saveSavedReply(id: $id, title: $title, body: $body) { id } }`,
  deleteSavedReply: gql`mutation DelReply($id: ID!) { deleteSavedReply(id: $id) }`,
  createIdea: gql`mutation CreateIdea($input: IdeaInput!) { createIdea(input: $input) { id } }`,
  updateIdea: gql`mutation UpdateIdea($id: ID!, $input: IdeaInput!) { updateIdea(id: $id, input: $input) { id } }`,
  moveIdea: gql`mutation MoveIdea($id: ID!, $groupId: ID, $sortOrder: Int!) { moveIdea(id: $id, groupId: $groupId, sortOrder: $sortOrder) }`,
  deleteIdea: gql`mutation DeleteIdea($id: ID!) { deleteIdea(id: $id) }`,
  createIdeaGroup: gql`mutation CreateIdeaGroup($name: String!) { createIdeaGroup(name: $name) { id } }`,
  renameIdeaGroup: gql`mutation RenameIdeaGroup($id: ID!, $name: String!) { renameIdeaGroup(id: $id, name: $name) { id } }`,
  deleteIdeaGroup: gql`mutation DeleteIdeaGroup($id: ID!) { deleteIdeaGroup(id: $id) }`,
  createTemplate: gql`mutation CreateTemplate($title: String!, $body: String!, $category: String, $personal: Boolean) { createTemplate(title: $title, body: $body, category: $category, personal: $personal) { id } }`,
  deleteTemplate: gql`mutation DeleteTemplate($id: ID!) { deleteTemplate(id: $id) }`,
  replyToComment: gql`mutation Reply($id: ID!, $text: String!) { replyToComment(id: $id, text: $text) { id repliedAt } }`,
  assignComment: gql`mutation Assign($id: ID!, $accountId: ID) { assignComment(id: $id, accountId: $accountId) { id assignedToAccountId assignee { id name email avatarUrl } } }`,
  setCommentTriage: gql`mutation Triage($id: ID!, $triage: String) { setCommentTriage(id: $id, triage: $triage) { id triage } }`,
  likeComment: gql`mutation Like($id: ID!, $reaction: String) { likeComment(id: $id, reaction: $reaction) }`,
  hideComment: gql`mutation Hide($id: ID!, $hidden: Boolean!) { hideComment(id: $id, hidden: $hidden) }`,
  deleteComment: gql`mutation DelComment($id: ID!) { deleteComment(id: $id) }`,
  resolveComments: gql`mutation Resolve($ids: [ID!], $all: Boolean, $olderThanDays: Int, $postExternalId: String, $channelId: ID, $resolved: Boolean) { resolveComments(ids: $ids, all: $all, olderThanDays: $olderThanDays, postExternalId: $postExternalId, channelId: $channelId, resolved: $resolved) }`,
  syncInbox: gql`mutation Sync($channelId: ID) { syncInbox(channelId: $channelId) }`,
  updateOrganization: gql`mutation UpdateOrg($name: String, $require2fa: Boolean, $settings: JSON) { updateOrganization(name: $name, require2fa: $require2fa, settings: $settings) { id } }`,
  inviteMember: gql`mutation Invite($email: String!, $role: OrgRole, $grants: [ChannelGrantInput!]) { inviteMember(email: $email, role: $role, grants: $grants) { id } }`,
  updateMember: gql`mutation UpdateMember($membershipId: ID!, $role: OrgRole, $grants: [ChannelGrantInput!]) { updateMember(membershipId: $membershipId, role: $role, grants: $grants) { id } }`,
  removeMember: gql`mutation RemoveMember($membershipId: ID!) { removeMember(membershipId: $membershipId) }`,
  acceptInvite: gql`mutation Accept($token: String!) { acceptInvite(token: $token) }`,
  switchOrganization: gql`mutation Switch($organizationId: ID!) { switchOrganization(organizationId: $organizationId) }`,
  createOrganization: gql`mutation CreateOrg($name: String!) { createOrganization(name: $name) { id slug } }`,
  updatePreferences: gql`mutation Prefs($input: PreferencesInput!) { updatePreferences(input: $input) }`,
  setNotificationPref: gql`mutation SetPref($key: String!, $enabled: Boolean!) { setNotificationPref(key: $key, enabled: $enabled) }`,
  createApiKey: gql`mutation CreateKey($name: String!, $scopes: [String!]!) { createApiKey(name: $name, scopes: $scopes) { key id } }`,
  revokeApiKey: gql`mutation RevokeKey($id: ID!) { revokeApiKey(id: $id) }`,
  saveView: gql`mutation SaveView($id: ID, $area: String!, $name: String!, $filters: JSON!) { saveView(id: $id, area: $area, name: $name, filters: $filters) { id } }`,
  deleteView: gql`mutation DeleteView($id: ID!) { deleteView(id: $id) }`,
};
